### PR TITLE
Querystring

### PR DESCRIPTION
**Pull request by mjumbewu**
Check for opt-out querystring parameter

### CODE REVIEW

**Comment by timwis** [comment]
@mjumbewu looks like you accidentally committed a bunch of static resources :-/

**Comment by mjumbewu** [comment]
It wasn't accidental. Those were things that made it work with my hosts
file rewrite. I can remove them though.

**Comment by mjumbewu** [comment]
Updated.

**Comment by timwis** [comment]
Thanks @mjumbewu !

**Pull request merged**
